server:
  port: 888


eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进eureka服务默认为true
    fetch-registry: true #是否从eureka抓取已有的注册信息,单节点无所谓 集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      # 集群
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #单机
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: cloud-order-service-888
    prefer-ip-address: true
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
        #
      probability: 1
