server:
  port: 892


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    fetch-registry: true
  instance:
    instance-id: cloud-order-service-892
    prefer-ip-address: true

spring:
  application:
    name: cloud-provider-hystrix-order



feign:
  hystrix:
    enabled: true #在feign开启Hystrix

